project_1:
  outputs:
    dev:
      dbname: project_1
      host: localhost
      pass: '1234'
      port: 5432
      schema: raw
      threads: 1
      type: postgres
      user: postgres
  target: dev